# Generated by Django 5.2.4 on 2025-08-25 01:28

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='encrypted_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
