# Generated by Django 5.2.4 on 2025-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('adoption', 'Adoption'), ('lost_found', 'Lost & Found'), ('services', 'Services')], default='services', max_length=50, null=True),
        ),
    ]
